host: MBPvonFrederic
Building DAG of jobs...
Using shell: /opt/local/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
all          1
exp          2
total        3

Select jobs to execute...
Execute 2 jobs...

[Tue Oct 22 15:03:22 2024]
localrule exp:
    input: results/__cythonized__
    output: results/pyr.csv
    jobid: 2
    reason: Code has changed since last execution
    wildcards: alg=pyr
    resources: tmpdir=/var/folders/dj/14c985vd1ng7gf0vvw_ytrpw0000gn/T

[Tue Oct 22 15:03:22 2024]
localrule exp:
    input: results/__cythonized__
    output: results/cx.csv
    jobid: 3
    reason: Code has changed since last execution
    wildcards: alg=cx
    resources: tmpdir=/var/folders/dj/14c985vd1ng7gf0vvw_ytrpw0000gn/T

RuleException:
CalledProcessError in file /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/workflow/Snakefile, line 27:
Command 'set -euo pipefail;  /Users/fredericbusch/miniforge3/envs/py-raccoon/bin/python3.12 /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/.snakemake/scripts/tmphh4r9735.compute.py' returned non-zero exit status 1.
[Tue Oct 22 15:03:26 2024]
Error in rule exp:
    jobid: 3
    input: results/__cythonized__
    output: results/cx.csv

RuleException:
CalledProcessError in file /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/workflow/Snakefile, line 27:
Command 'set -euo pipefail;  /Users/fredericbusch/miniforge3/envs/py-raccoon/bin/python3.12 /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/.snakemake/scripts/tmpubp7s58u.compute.py' returned non-zero exit status 1.
[Tue Oct 22 15:03:26 2024]
Error in rule exp:
    jobid: 2
    input: results/__cythonized__
    output: results/pyr.csv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-22T150322.488186.snakemake.log
WorkflowError:
At least one job did not complete successfully.
