host: fredduuxd
Building DAG of jobs...
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job             count
------------  -------
combine_exps        1
cythonize           1
random_pyr          1
test                1
total               4

Select jobs to execute...
Execute 1 jobs...

[Mon Nov 11 01:28:49 2024]
localrule cythonize:
    input: src/py_raccoon/balance_sampling.pyx, src/py_raccoon/balance_spanning_trees.pyx
    output: results/__cythonized__
    jobid: 3
    reason: Missing output files: results/__cythonized__
    resources: tmpdir=C:\Users\FREDDU~1\AppData\Local\Temp

[Mon Nov 11 01:28:49 2024]
Finished job 3.
1 of 4 steps (25%) done
Select jobs to execute...
Execute 1 jobs...

[Mon Nov 11 01:28:49 2024]
localrule random_pyr:
    input: results/__cythonized__
    output: results/synthetic/random/n=20 m=50 r=0.5 d=False/pyr/s=1000 sp=1/run/pyr_0.csv
    jobid: 2
    reason: Missing output files: results/synthetic/random/n=20 m=50 r=0.5 d=False/pyr/s=1000 sp=1/run/pyr_0.csv; Input files updated by another job: results/__cythonized__
    wildcards: n_nodes=20, n_edges=50, neg_edge_prob=0.5, n_samples=1000, pyr_spec_edge_prob=1, run=0
    resources: tmpdir=C:\Users\FREDDU~1\AppData\Local\Temp

RuleException:
CalledProcessError in file C:\Users\fredduuxd\Desktop\Thesis\py-raccoon\workflow\Snakefile, line 64:
Command 'C:/Users/fredduuxd/miniforge3/envs/py-raccoon/python.exe "C:\Users\fredduuxd\Desktop\Thesis\py-raccoon\.snakemake\scripts\tmp8_h1l1gr.experiment.py"' returned non-zero exit status 1.
[Mon Nov 11 01:28:51 2024]
Error in rule random_pyr:
    jobid: 2
    input: results/__cythonized__
    output: results/synthetic/random/n=20 m=50 r=0.5 d=False/pyr/s=1000 sp=1/run/pyr_0.csv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-11-11T012849.164027.snakemake.log
WorkflowError:
At least one job did not complete successfully.
