host: MacBook-Pro-von-Frederic.local
Building DAG of jobs...
Using shell: /opt/local/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Job stats:
job             count
------------  -------
combine_exps        1
random_pyr          1
test                1
total               3

Select jobs to execute...
Execute 1 jobs...

[Mon Nov 11 21:14:43 2024]
localrule random_pyr:
    input: results/__cythonized__
    output: results/synthetic/random/n=10 m=10 r=5 re=True d=False/pyr/s=1000 sp=None/run/run/pyr_0.csv
    jobid: 2
    reason: Missing output files: results/synthetic/random/n=10 m=10 r=5 re=True d=False/pyr/s=1000 sp=None/run/run/pyr_0.csv
    wildcards: n_nodes=10, n_edges=10, neg_edge_prob=5, neg_edge_dist_exact=True, directed=False, n_samples=1000, pyr_spec_edge_prob=None/run, run=0
    resources: tmpdir=/var/folders/dj/14c985vd1ng7gf0vvw_ytrpw0000gn/T

RuleException:
CalledProcessError in file /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/workflow/Snakefile, line 73:
Command 'set -euo pipefail;  /Users/fredericbusch/miniforge3/envs/py-raccoon/bin/python3.12 /Users/fredericbusch/Desktop/Thesis/forks/py-raccoon/.snakemake/scripts/tmpr530yumd.experiment.py' returned non-zero exit status 1.
[Mon Nov 11 21:14:45 2024]
Error in rule random_pyr:
    jobid: 2
    input: results/__cythonized__
    output: results/synthetic/random/n=10 m=10 r=5 re=True d=False/pyr/s=1000 sp=None/run/run/pyr_0.csv

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-11-11T211443.147713.snakemake.log
WorkflowError:
At least one job did not complete successfully.
